#!/usr/bin/env python3
"""
CLI utility to inspect, audit, and verify the status, freshness, and rich metadata of
executive podcast briefings generated by Gemini 3.5 Flash across Project Dash workspaces.

Provides detailed metadata including:
- Podcast duration/length (audio duration or script reading estimate, turns, word count)
- Size (audio file size in MB or script size in KB)
- Date of generation (timestamp when Gemini generated the briefing)
- Data ingestion timestamp (when the weekly PDF/data was ingested into the project)
- Speaker roles and cast details

Usage:
  python3 scripts/check_podcast_status.py
  python3 scripts/check_podcast_status.py --project monaro
  python3 scripts/check_podcast_status.py --project monaro --fix
  python3 scripts/check_podcast_status.py --json
  python3 scripts/check_podcast_status.py --table-only
  python3 scripts/check_podcast_status.py --script
"""

import os
import sys
import json
import argparse
import re
from typing import Dict, Any, List, Optional, Tuple
from datetime import datetime, timezone

# Ensure project root is in sys.path
PARENT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if PARENT_DIR not in sys.path:
    sys.path.insert(0, PARENT_DIR)

from scripts.pipeline import get_project_dir, load_json_file, DATA_BASE_DIR
from scripts.sync_drive import ensure_latest_podcast_generated


def parse_time_str(time_str: Optional[str]) -> Optional[int]:
    """Parses 'M:SS' or 'H:MM:SS' time strings into integer seconds."""
    if not time_str or not isinstance(time_str, str):
        return None
    parts = time_str.strip().split(':')
    try:
        if len(parts) == 2:
            return int(parts[0]) * 60 + int(parts[1])
        elif len(parts) == 3:
            return int(parts[0]) * 3600 + int(parts[1]) * 60 + int(parts[2])
    except (ValueError, TypeError):
        return None
    return None


def format_duration(seconds: Optional[float]) -> str:
    """Formats seconds into human-readable 'Xm YYs'."""
    if seconds is None or seconds <= 0:
        return "0m 00s"
    total_secs = int(round(seconds))
    mins = total_secs // 60
    secs = total_secs % 60
    return f"{mins}m {secs:02d}s"


def format_bytes(size_bytes: Optional[int]) -> str:
    """Formats byte count into human-readable B, KB, or MB."""
    if size_bytes is None:
        return "None"
    if size_bytes < 1024:
        return f"{size_bytes} B"
    elif size_bytes < 1024 * 1024:
        return f"{size_bytes / 1024:.1f} KB"
    else:
        return f"{size_bytes / (1024 * 1024):.2f} MB"


def format_datetime_display(dt_val: Optional[Any]) -> str:
    """Formats an ISO timestamp or date string cleanly into 'YYYY-MM-DD HH:MM:SS UTC'."""
    if not dt_val:
        return "--"
    val_str = str(dt_val).strip()
    try:
        clean_str = val_str.replace('Z', '+00:00')
        dt = datetime.fromisoformat(clean_str)
        if dt.tzinfo:
            dt = dt.astimezone(timezone.utc)
            return dt.strftime("%Y-%m-%d %H:%M:%S UTC")
        return dt.strftime("%Y-%m-%d %H:%M:%S")
    except Exception:
        pass
    return val_str[:25]


def resolve_audio_asset(project_name: str, max_week: int, proj_dir: str) -> Tuple[bool, Optional[str], Optional[int], Optional[float]]:
    """
    Finds candidate audio files for a given project and week.
    Returns (has_audio_file, audio_path, audio_size_bytes, audio_duration_seconds).
    """
    candidate_audio_paths = [
        os.path.join(proj_dir, f"podcast_w{max_week}.mp3"),
        os.path.join(proj_dir, f"podcast_{project_name}_w{max_week}.mp3"),
        os.path.join(PARENT_DIR, 'assets', f"podcast_{project_name}_w{max_week}.mp3"),
    ]
    if project_name == 'monaro':
        candidate_audio_paths.extend([
            os.path.join(PARENT_DIR, 'assets', f"podcast_w{max_week}.mp3"),
            os.path.join(PARENT_DIR, 'assets', f"podcast_w{max_week}.wav"),
            os.path.join(proj_dir, 'podcast.mp3'),
        ])
    elif project_name == 'sample':
        candidate_audio_paths.extend([
            os.path.join(proj_dir, 'podcast_sample.mp3'),
            os.path.join(PARENT_DIR, 'assets', 'podcast_sample.mp3'),
        ])

    audio_asset_path = None
    for cand in candidate_audio_paths:
        if os.path.isfile(cand):
            audio_asset_path = cand
            break

    if not audio_asset_path:
        return False, None, None, None

    audio_size_bytes = os.path.getsize(audio_asset_path)
    audio_duration_seconds = None

    try:
        import mutagen
        from mutagen.mp3 import MP3
        from mutagen.wave import WAVE
        if audio_asset_path.lower().endswith('.mp3'):
            a = MP3(audio_asset_path)
            audio_duration_seconds = getattr(a.info, 'length', None)
        elif audio_asset_path.lower().endswith('.wav'):
            a = WAVE(audio_asset_path)
            audio_duration_seconds = getattr(a.info, 'length', None)
        else:
            a = mutagen.File(audio_asset_path)
            if a is not None and hasattr(a, 'info') and hasattr(a.info, 'length'):
                audio_duration_seconds = a.info.length
    except Exception:
        pass

    return True, audio_asset_path, audio_size_bytes, audio_duration_seconds


def calculate_script_metrics(podcast_script: List[Dict[str, Any]]) -> Dict[str, Any]:
    """Calculates word count, character count, estimated duration, and speaker details from script."""
    turn_count = len(podcast_script)
    total_words = 0
    total_chars = 0
    speakers = []
    speakers_detail = []
    seen_speakers = set()

    for t in podcast_script:
        if isinstance(t, dict):
            text = str(t.get('text', ''))
            words = len(text.split())
            total_words += words
            total_chars += len(text)

            spk = t.get('speaker')
            if spk and spk not in seen_speakers:
                seen_speakers.add(spk)
                speakers.append(spk)
                speakers_detail.append({
                    'speaker': spk,
                    'role': t.get('role', 'Speaker'),
                    'avatar': t.get('avatar', '🎙️')
                })

    # Duration estimation: conversational speaking rate ~135-140 words/min
    wpm_est_seconds = int((total_words / 135.0) * 60) if total_words else 0

    # Timestamp-based check from final turn
    timestamp_est_seconds = 0
    if podcast_script:
        last_turn = podcast_script[-1]
        if isinstance(last_turn, dict):
            last_time = parse_time_str(last_turn.get('time', ''))
            if last_time is not None:
                last_words = len(str(last_turn.get('text', '')).split())
                last_turn_dur = int((last_words / 135.0) * 60)
                timestamp_est_seconds = last_time + max(last_turn_dur, 4)

    est_seconds = max(wpm_est_seconds, timestamp_est_seconds)
    script_json_bytes = len(json.dumps(podcast_script, ensure_ascii=False).encode('utf-8'))

    return {
        'turn_count': turn_count,
        'word_count': total_words,
        'char_count': total_chars,
        'script_size_bytes': script_json_bytes,
        'script_size_formatted': format_bytes(script_json_bytes),
        'duration_seconds': est_seconds,
        'duration_formatted': format_duration(est_seconds),
        'speakers': speakers,
        'speakers_detail': speakers_detail
    }


def check_project_podcast_status(
    project_name: str,
    data_root: Optional[str] = None
) -> Dict[str, Any]:
    """
    Inspects a project's snapshots.json and returns a comprehensive structured audit
    of its podcast status and metadata (size, dates, ingestion timestamp, length).
    """
    proj_dir = get_project_dir(project_name, data_root)
    snapshots_path = os.path.join(proj_dir, 'snapshots.json')

    if not os.path.exists(snapshots_path):
        return {
            'project': project_name,
            'snapshots_path': snapshots_path,
            'exists': False,
            'total_snapshots': 0,
            'latest_week': None,
            'latest_week_number': None,
            'latest_week_key': None,
            'has_podcast': False,
            'turn_count': 0,
            'word_count': 0,
            'char_count': 0,
            'speakers': [],
            'speakers_detail': [],
            'generated_by': None,
            'is_gemini_35': False,
            'is_up_to_date': False,
            'generated_at': None,
            'generated_at_formatted': "--",
            'data_ingested_at': None,
            'data_ingested_at_formatted': "--",
            'data_source_file': None,
            'duration_seconds': 0,
            'duration_formatted': "0m 00s",
            'length': "0m 00s (0 turns)",
            'length_type': "none",
            'size_bytes': 0,
            'size_formatted': "N/A",
            'size_summary': "N/A",
            'audio_size_bytes': None,
            'audio_size_formatted': "None",
            'script_size_bytes': 0,
            'script_size_formatted': "0 B",
            'has_audio_asset': False,
            'audio_asset_path': None,
            'status': 'NO_DATA',
            'details': f"No snapshots.json found at {snapshots_path}"
        }

    snapshots_data = load_json_file(snapshots_path, {})
    is_wrapped = 'snapshots' in snapshots_data and isinstance(snapshots_data['snapshots'], dict)
    snapshots_map = snapshots_data['snapshots'] if is_wrapped else snapshots_data

    max_week = -1
    latest_key = None
    latest_snap = None

    for k, v in snapshots_map.items():
        if not isinstance(v, dict):
            continue
        wn = v.get('weekNumber')
        if wn is not None:
            try:
                wn_val = int(wn)
                if wn_val > max_week:
                    max_week = wn_val
                    latest_key = k
                    latest_snap = v
            except (ValueError, TypeError):
                pass
        m = re.search(r'\d+', str(k))
        if m:
            try:
                wn_val = int(m.group(0))
                if wn_val > max_week:
                    max_week = wn_val
                    latest_key = k
                    latest_snap = v
            except (ValueError, TypeError):
                pass

    if not latest_snap:
        return {
            'project': project_name,
            'snapshots_path': snapshots_path,
            'exists': True,
            'total_snapshots': len(snapshots_map),
            'latest_week': None,
            'latest_week_number': None,
            'latest_week_key': None,
            'has_podcast': False,
            'turn_count': 0,
            'word_count': 0,
            'char_count': 0,
            'speakers': [],
            'speakers_detail': [],
            'generated_by': None,
            'is_gemini_35': False,
            'is_up_to_date': False,
            'generated_at': None,
            'generated_at_formatted': "--",
            'data_ingested_at': None,
            'data_ingested_at_formatted': "--",
            'data_source_file': None,
            'duration_seconds': 0,
            'duration_formatted': "0m 00s",
            'length': "0m 00s (0 turns)",
            'length_type': "none",
            'size_bytes': 0,
            'size_formatted': "N/A",
            'size_summary': "N/A",
            'audio_size_bytes': None,
            'audio_size_formatted': "None",
            'script_size_bytes': 0,
            'script_size_formatted': "0 B",
            'has_audio_asset': False,
            'audio_asset_path': None,
            'status': 'EMPTY_SNAPSHOTS',
            'details': "Snapshots file exists but contains no valid weekly snapshots"
        }

    latest_week_label = latest_snap.get('weekLabel') or latest_snap.get('week') or f"Week {max_week}"
    podcast_script = latest_snap.get('podcastScript') or []
    has_podcast = isinstance(podcast_script, list) and len(podcast_script) > 0

    # Calculate script metrics
    script_metrics = calculate_script_metrics(podcast_script if has_podcast else [])

    generated_by = (
        latest_snap.get('podcastGeneratedBy') or
        latest_snap.get('generatedBy') or
        ('gemini-3.5-flash' if (has_podcast and any(t.get('time') for t in podcast_script)) else 'deterministic_rule_engine')
    )
    is_gemini_35 = (generated_by == 'gemini-3.5-flash')

    # Audio asset check
    has_audio_file, audio_asset_path, audio_size_bytes, audio_dur_secs = resolve_audio_asset(
        project_name, max_week, proj_dir
    )

    # Resolve podcast duration and length
    if has_audio_file and audio_dur_secs is not None:
        duration_seconds = int(round(audio_dur_secs))
        duration_formatted = format_duration(duration_seconds)
        length_type = "audio"
        length_desc = f"{duration_formatted} ({script_metrics['turn_count']} turns, {script_metrics['word_count']} words)"
    elif has_podcast:
        duration_seconds = script_metrics['duration_seconds']
        duration_formatted = script_metrics['duration_formatted']
        length_type = "script_estimate"
        length_desc = f"{duration_formatted} ({script_metrics['turn_count']} turns, {script_metrics['word_count']} words)"
    else:
        duration_seconds = 0
        duration_formatted = "0m 00s"
        length_type = "none"
        length_desc = "0m 00s (0 turns)"

    # Resolve podcast size
    if has_audio_file and audio_size_bytes:
        size_bytes = audio_size_bytes
        size_formatted = format_bytes(audio_size_bytes)
        audio_size_formatted = size_formatted
        size_summary = f"{size_formatted} (Audio MP3)"
    elif has_podcast:
        size_bytes = script_metrics['script_size_bytes']
        size_formatted = script_metrics['script_size_formatted']
        audio_size_formatted = "None (Speech Synthesis)"
        size_summary = f"{size_formatted} (Script)"
    else:
        size_bytes = 0
        size_formatted = "0 B"
        audio_size_formatted = "None"
        size_summary = "None"

    # Resolve date of generation
    generated_at = (
        latest_snap.get('podcastGeneratedAt') or
        latest_snap.get('generatedAt')
    )
    if not generated_at and has_audio_file and audio_asset_path:
        try:
            mtime = os.path.getmtime(audio_asset_path)
            generated_at = datetime.fromtimestamp(mtime, tz=timezone.utc).isoformat()
        except Exception:
            pass
    if not generated_at:
        generated_at = snapshots_data.get('lastSynced')
    if not generated_at and latest_snap:
        generated_at = latest_snap.get('driveFile', {}).get('ingestedAt')
    if not generated_at and os.path.exists(snapshots_path):
        try:
            mtime = os.path.getmtime(snapshots_path)
            generated_at = datetime.fromtimestamp(mtime, tz=timezone.utc).isoformat()
        except Exception:
            pass

    generated_at_formatted = format_datetime_display(generated_at)

    # Resolve when the data for the week was ingested
    data_ingested_at = None
    data_source_file = None
    if latest_snap:
        drive_file_meta = latest_snap.get('driveFile')
        if isinstance(drive_file_meta, dict):
            data_ingested_at = drive_file_meta.get('ingestedAt')
            data_source_file = drive_file_meta.get('name')
        if not data_source_file:
            data_source_file = latest_snap.get('driveFileName')
        if not data_ingested_at:
            data_ingested_at = latest_snap.get('ingestedAt')
        if not data_ingested_at:
            data_ingested_at = latest_snap.get('date')
    if not data_ingested_at:
        data_ingested_at = snapshots_data.get('lastSynced')

    data_ingested_at_formatted = format_datetime_display(data_ingested_at)

    # Status determination
    if not has_podcast:
        status = 'MISSING_PODCAST'
        details = f"Latest snapshot '{latest_key}' ({latest_week_label}) has no podcast script"
    elif not is_gemini_35:
        status = 'NEEDS_REGENERATION'
        details = f"Latest snapshot '{latest_key}' ({latest_week_label}) is using fallback '{generated_by}', not gemini-3.5-flash"
    elif not has_audio_file:
        status = 'AUDIO_MISSING'
        details = f"Latest snapshot '{latest_key}' ({latest_week_label}) has script by {generated_by} but audio MP3 file is missing on disk"
    else:
        status = 'UP_TO_DATE'
        details = f"Latest snapshot '{latest_key}' ({latest_week_label}) generated by {generated_by} with Chirp 3 HD audio ({script_metrics['turn_count']} turns, {duration_formatted})"

    is_up_to_date = (status == 'UP_TO_DATE')

    return {
        'project': project_name,
        'snapshots_path': snapshots_path,
        'exists': True,
        'total_snapshots': len(snapshots_map),
        'latest_week': latest_week_label,
        'latest_week_number': max_week,
        'latest_week_key': latest_key,
        'has_podcast': has_podcast,
        'turn_count': script_metrics['turn_count'],
        'word_count': script_metrics['word_count'],
        'char_count': script_metrics['char_count'],
        'speakers': script_metrics['speakers'],
        'speakers_detail': script_metrics['speakers_detail'],
        'generated_by': generated_by,
        'is_gemini_35': is_gemini_35,
        'is_up_to_date': is_up_to_date,
        'generated_at': generated_at,
        'generated_at_formatted': generated_at_formatted,
        'data_ingested_at': data_ingested_at,
        'data_ingested_at_formatted': data_ingested_at_formatted,
        'data_source_file': data_source_file,
        'duration_seconds': duration_seconds,
        'duration_formatted': duration_formatted,
        'length': length_desc,
        'length_type': length_type,
        'size_bytes': size_bytes,
        'size_formatted': size_formatted,
        'size_summary': size_summary,
        'audio_size_bytes': audio_size_bytes,
        'audio_size_formatted': audio_size_formatted,
        'script_size_bytes': script_metrics['script_size_bytes'],
        'script_size_formatted': script_metrics['script_size_formatted'],
        'has_audio_asset': has_audio_file,
        'audio_asset_path': audio_asset_path,
        'podcast_script': podcast_script if has_podcast else [],
        'status': status,
        'details': details
    }


def check_all_projects(
    data_root: Optional[str] = None,
    projects: Optional[List[str]] = None
) -> List[Dict[str, Any]]:
    """Inspects all discovered or specified projects."""
    root = data_root or DATA_BASE_DIR
    target_projects = projects
    if not target_projects:
        if os.path.exists(root):
            target_projects = [
                d for d in sorted(os.listdir(root))
                if os.path.isdir(os.path.join(root, d))
                and not d.startswith('.')
                and (os.path.exists(os.path.join(root, d, 'snapshots.json')) or os.path.exists(os.path.join(root, d, 'config.json')))
            ]
        else:
            target_projects = ['monaro', 'sample']

    results = []
    for p in target_projects:
        results.append(check_project_podcast_status(p, data_root=data_root))
    return results


def print_status_table(reports: List[Dict[str, Any]]) -> bool:
    """Prints a clean summary status table to stdout. Returns True if all projects are UP_TO_DATE."""
    table_width = 116
    print("=" * table_width)
    print("  PROJECT DASH - PODCAST GENERATION AUDIT & STATUS OVERVIEW (Gemini 3.5 Flash)")
    print("=" * table_width)
    header = f"{'PROJECT':<10} | {'WEEK':<8} | {'STATUS':<16} | {'LENGTH':<12} | {'SIZE':<14} | {'DATA INGESTED':<19} | {'GENERATED AT':<19}"
    print(header)
    print("-" * table_width)

    all_ok = True
    for r in reports:
        proj = r['project']
        wk = r['latest_week'] or '--'
        status = r['status']
        dur = f"{r['duration_formatted']} ({r['turn_count']}t)"
        sz = r['size_summary']
        ingested = r['data_ingested_at_formatted']
        generated = r['generated_at_formatted']

        # Shorten timestamps for table column width if needed
        if len(ingested) > 19:
            ingested = ingested[:19]
        if len(generated) > 19:
            generated = generated[:19]

        status_icon = "🟢" if status == "UP_TO_DATE" else ("🟡" if status == "NEEDS_REGENERATION" else "🔴")
        display_status = f"{status_icon} {status}"

        if not r['is_up_to_date']:
            all_ok = False

        print(f"{proj:<10} | {wk:<8} | {display_status:<16} | {dur:<12} | {sz:<14} | {ingested:<19} | {generated:<19}")

    print("=" * table_width)
    return all_ok


def print_project_metadata_card(report: Dict[str, Any], show_script: bool = False):
    """Prints a detailed executive metadata card for a project's podcast."""
    card_width = 96
    proj = report['project']
    week = report['latest_week'] or 'Unknown Week'
    status = report['status']
    status_icon = "🟢" if status == "UP_TO_DATE" else ("🟡" if status == "NEEDS_REGENERATION" else "🔴")

    print("\n" + "-" * card_width)
    print(f"🎙️  PROJECT PODCAST METADATA: {proj.upper()} • {week} ({status_icon} {status})")
    print("-" * card_width)

    print(f"  • Status:               {status_icon} {status} ({report['details']})")
    print(f"  • Generation Model:     {report.get('generated_by') or 'None'}")
    print(f"  • Date of Generation:   {report.get('generated_at_formatted') or '--'}")
    print(f"  • Data Ingested At:     {report.get('data_ingested_at_formatted') or '--'}")
    if report.get('data_source_file'):
        print(f"  • Data Source File:     {report['data_source_file']}")
    
    length_note = "(Actual Audio MP3)" if report.get('length_type') == 'audio' else "(Estimated speaking pace)"
    print(f"  • Podcast Length:       {report.get('duration_formatted')} {length_note}")
    print(f"  • Dialogue Scope:       {report.get('turn_count')} dialogue turns • {report.get('word_count')} words • {report.get('char_count')} chars")

    audio_note = f"✓ File Present ({report.get('audio_size_formatted')})" if report.get('has_audio_asset') else "✗ Browser Speech Synthesis (No MP3 asset)"
    print(f"  • Podcast Size:         {report.get('size_summary')} (Script: {report.get('script_size_formatted')})")
    print(f"  • Audio Asset:          {audio_note}")
    if report.get('audio_asset_path'):
        print(f"  • Audio File Path:      {report['audio_asset_path']}")

    speakers_fmt = ", ".join([f"{s['speaker']} ({s['role']})" for s in report.get('speakers_detail', [])])
    if not speakers_fmt:
        speakers_fmt = ", ".join(report.get('speakers', [])) or "None"
    print(f"  • Cast & Roles:         {speakers_fmt}")

    if show_script and report.get('podcast_script'):
        print("\n  📝 Dialogue Script:")
        for idx, turn in enumerate(report['podcast_script'], start=1):
            time_tag = f"[{turn.get('time', '0:00')}]" if turn.get('time') else ""
            spk = turn.get('speaker', 'Speaker')
            avatar = turn.get('avatar', '🎙️')
            role = f"({turn.get('role')})" if turn.get('role') else ""
            txt = turn.get('text', '')
            print(f"    {time_tag} {avatar} {spk} {role}: {txt}")

    print("-" * card_width)


def main():
    parser = argparse.ArgumentParser(
        description="Inspect, audit, and display rich metadata for executive podcast generation across Project Dash workspaces."
    )
    parser.add_argument(
        '--project',
        default=None,
        help="Target project slug (e.g. monaro, sample). If omitted, all projects are audited."
    )
    parser.add_argument(
        '--data-root',
        default=None,
        help="Custom path to data root directory."
    )
    parser.add_argument(
        '--fix',
        action='store_true',
        help="Attempt automatic regeneration of missing or outdated podcast scripts using Gemini 3.5 Flash."
    )
    parser.add_argument(
        '--json',
        action='store_true',
        help="Output complete structured JSON format instead of human-readable text output."
    )
    parser.add_argument(
        '--table-only',
        action='store_true',
        help="Display only the summary overview table without detailed project metadata cards."
    )
    parser.add_argument(
        '--script',
        action='store_true',
        help="Include full dialogue script text in detailed project metadata cards."
    )

    args = parser.parse_args()

    target_projects = [args.project] if args.project else None
    reports = check_all_projects(data_root=args.data_root, projects=target_projects)

    if args.fix:
        for r in reports:
            if not r['is_up_to_date'] and r['exists']:
                print(f"[*] Regenerating podcast briefing for project '{r['project']}' with Gemini 3.5 Flash...")
                try:
                    updated = ensure_latest_podcast_generated(
                        project_name=r['project'],
                        data_root=args.data_root,
                        force=True
                    )
                    if updated:
                        print(f"  ✓ Successfully regenerated podcast for project '{r['project']}'")
                    else:
                        print(f"  ✗ Regeneration did not produce updates for '{r['project']}'")
                except Exception as e:
                    print(f"  ✗ Regeneration error for '{r['project']}': {e}")
        # Refresh reports after fix attempts
        reports = check_all_projects(data_root=args.data_root, projects=target_projects)

    if args.json:
        # Strip internal full script if not asked to keep JSON clean unless desired
        print(json.dumps(reports, indent=2))
        all_ok = all(r['is_up_to_date'] for r in reports)
        sys.exit(0 if all_ok else 1)

    all_ok = print_status_table(reports)

    if not args.table_only:
        for r in reports:
            print_project_metadata_card(r, show_script=args.script)

    sys.exit(0 if all_ok else 1)


if __name__ == '__main__':
    main()
