#!/usr/bin/env python3
"""
CLI utility to inspect, audit, and verify the status and freshness of executive podcast
briefings generated by Gemini 3.5 Flash across Project Dash project workspaces.

Usage:
  python3 scripts/check_podcast_status.py
  python3 scripts/check_podcast_status.py --project monaro
  python3 scripts/check_podcast_status.py --project monaro --fix
  python3 scripts/check_podcast_status.py --json
"""

import os
import sys
import json
import argparse
import re
from typing import Dict, Any, List, Optional
from datetime import datetime

# Ensure project root is in sys.path
PARENT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if PARENT_DIR not in sys.path:
    sys.path.insert(0, PARENT_DIR)

from scripts.pipeline import get_project_dir, load_json_file, DATA_BASE_DIR
from scripts.sync_drive import ensure_latest_podcast_generated


def check_project_podcast_status(
    project_name: str,
    data_root: Optional[str] = None
) -> Dict[str, Any]:
    """
    Inspects a project's snapshots.json and returns a structured audit of its podcast status.
    """
    proj_dir = get_project_dir(project_name, data_root)
    snapshots_path = os.path.join(proj_dir, 'snapshots.json')

    if not os.path.exists(snapshots_path):
        return {
            'project': project_name,
            'snapshots_path': snapshots_path,
            'exists': False,
            'total_snapshots': 0,
            'latest_week': None,
            'latest_week_key': None,
            'has_podcast': False,
            'turn_count': 0,
            'speakers': [],
            'generated_by': None,
            'is_gemini_35': False,
            'is_up_to_date': False,
            'status': 'NO_DATA',
            'details': f"No snapshots.json found at {snapshots_path}"
        }

    snapshots_data = load_json_file(snapshots_path, {})
    is_wrapped = 'snapshots' in snapshots_data and isinstance(snapshots_data['snapshots'], dict)
    snapshots_map = snapshots_data['snapshots'] if is_wrapped else snapshots_data

    max_week = -1
    latest_key = None
    latest_snap = None

    for k, v in snapshots_map.items():
        if not isinstance(v, dict):
            continue
        wn = v.get('weekNumber')
        if wn is not None:
            try:
                wn_val = int(wn)
                if wn_val > max_week:
                    max_week = wn_val
                    latest_key = k
                    latest_snap = v
            except (ValueError, TypeError):
                pass
        m = re.search(r'\d+', str(k))
        if m:
            try:
                wn_val = int(m.group(0))
                if wn_val > max_week:
                    max_week = wn_val
                    latest_key = k
                    latest_snap = v
            except (ValueError, TypeError):
                pass

    if not latest_snap:
        return {
            'project': project_name,
            'snapshots_path': snapshots_path,
            'exists': True,
            'total_snapshots': len(snapshots_map),
            'latest_week': None,
            'latest_week_key': None,
            'has_podcast': False,
            'turn_count': 0,
            'speakers': [],
            'generated_by': None,
            'is_gemini_35': False,
            'is_up_to_date': False,
            'status': 'EMPTY_SNAPSHOTS',
            'details': "Snapshots file exists but contains no valid weekly snapshots"
        }

    latest_week_label = latest_snap.get('weekLabel') or latest_snap.get('week') or f"Week {max_week}"
    podcast_script = latest_snap.get('podcastScript') or []
    has_podcast = isinstance(podcast_script, list) and len(podcast_script) > 0
    turn_count = len(podcast_script) if has_podcast else 0
    speakers = list(dict.fromkeys([t.get('speaker') for t in podcast_script if isinstance(t, dict) and t.get('speaker')]))

    generated_by = (
        latest_snap.get('podcastGeneratedBy') or
        latest_snap.get('generatedBy') or
        ('gemini-3.5-flash' if (has_podcast and any(t.get('time') for t in podcast_script)) else 'deterministic_rule_engine')
    )
    is_gemini_35 = (generated_by == 'gemini-3.5-flash')

    # Audio asset check
    assets_dir = os.path.join(PARENT_DIR, 'assets')
    audio_file_name = f"podcast_w{max_week}.mp3"
    audio_asset_path = os.path.join(assets_dir, audio_file_name)
    has_audio_file = os.path.exists(audio_asset_path)

    if not has_podcast:
        status = 'MISSING_PODCAST'
        details = f"Latest snapshot '{latest_key}' ({latest_week_label}) has no podcast script"
    elif not is_gemini_35:
        status = 'NEEDS_REGENERATION'
        details = f"Latest snapshot '{latest_key}' ({latest_week_label}) is using fallback '{generated_by}', not gemini-3.5-flash"
    else:
        status = 'UP_TO_DATE'
        details = f"Latest snapshot '{latest_key}' ({latest_week_label}) is generated by {generated_by} ({turn_count} turns)"

    is_up_to_date = (status == 'UP_TO_DATE')

    return {
        'project': project_name,
        'snapshots_path': snapshots_path,
        'exists': True,
        'total_snapshots': len(snapshots_map),
        'latest_week': latest_week_label,
        'latest_week_number': max_week,
        'latest_week_key': latest_key,
        'has_podcast': has_podcast,
        'turn_count': turn_count,
        'speakers': speakers,
        'generated_by': generated_by,
        'is_gemini_35': is_gemini_35,
        'is_up_to_date': is_up_to_date,
        'has_audio_asset': has_audio_file,
        'audio_asset_path': audio_asset_path if has_audio_file else None,
        'status': status,
        'details': details
    }


def check_all_projects(
    data_root: Optional[str] = None,
    projects: Optional[List[str]] = None
) -> List[Dict[str, Any]]:
    """Inspects all discovered or specified projects."""
    root = data_root or DATA_BASE_DIR
    target_projects = projects
    if not target_projects:
        if os.path.exists(root):
            target_projects = [
                d for d in sorted(os.listdir(root))
                if os.path.isdir(os.path.join(root, d))
                and not d.startswith('.')
                and (os.path.exists(os.path.join(root, d, 'snapshots.json')) or os.path.exists(os.path.join(root, d, 'config.json')))
            ]
        else:
            target_projects = ['monaro', 'sample']

    results = []
    for p in target_projects:
        results.append(check_project_podcast_status(p, data_root=data_root))
    return results


def print_status_table(reports: List[Dict[str, Any]]) -> bool:
    """Prints a clean status table to stdout. Returns True if all projects are UP_TO_DATE."""
    print("=" * 88)
    print("  PROJECT DASH - PODCAST GENERATION AUDIT & STATUS CHECK (Gemini 3.5 Flash)")
    print("=" * 88)
    header = f"{'PROJECT':<14} | {'LATEST WEEK':<12} | {'TURNS':<6} | {'GENERATED BY':<22} | {'STATUS':<16} | {'AUDIO FILE'}"
    print(header)
    print("-" * 88)

    all_ok = True
    for r in reports:
        proj = r['project']
        wk = r['latest_week'] or '--'
        turns = str(r['turn_count'])
        gen = str(r['generated_by'] or '--')
        status = r['status']
        audio = "✓ Present" if r.get('has_audio_asset') else "✗ None (Speech)"

        status_icon = "🟢" if status == "UP_TO_DATE" else ("🟡" if status == "NEEDS_REGENERATION" else "🔴")
        display_status = f"{status_icon} {status}"

        if not r['is_up_to_date']:
            all_ok = False

        print(f"{proj:<14} | {wk:<12} | {turns:<6} | {gen:<22} | {display_status:<16} | {audio}")

    print("=" * 88)
    return all_ok


def main():
    parser = argparse.ArgumentParser(
        description="Inspect and verify executive podcast generation status across Project Dash workspaces."
    )
    parser.add_argument(
        '--project',
        default=None,
        help="Target project slug (e.g. monaro, sample). If omitted, all projects are audited."
    )
    parser.add_argument(
        '--data-root',
        default=None,
        help="Custom path to data root directory."
    )
    parser.add_argument(
        '--fix',
        action='store_true',
        help="Attempt automatic regeneration of missing or outdated podcast scripts using Gemini 3.5 Flash."
    )
    parser.add_argument(
        '--json',
        action='store_true',
        help="Output raw JSON format instead of human-readable text table."
    )

    args = parser.parse_args()

    target_projects = [args.project] if args.project else None
    reports = check_all_projects(data_root=args.data_root, projects=target_projects)

    if args.fix:
        for r in reports:
            if not r['is_up_to_date'] and r['exists']:
                print(f"[*] Regenerating podcast briefing for project '{r['project']}' with Gemini 3.5 Flash...")
                try:
                    updated = ensure_latest_podcast_generated(
                        project_name=r['project'],
                        data_root=args.data_root,
                        force=True
                    )
                    if updated:
                        print(f"  ✓ Successfully regenerated podcast for project '{r['project']}'")
                    else:
                        print(f"  ✗ Regeneration did not produce updates for '{r['project']}'")
                except Exception as e:
                    print(f"  ✗ Regeneration error for '{r['project']}': {e}")
        # Refresh reports after fix attempts
        reports = check_all_projects(data_root=args.data_root, projects=target_projects)

    if args.json:
        print(json.dumps(reports, indent=2))
        all_ok = all(r['is_up_to_date'] for r in reports)
        sys.exit(0 if all_ok else 1)

    all_ok = print_status_table(reports)
    sys.exit(0 if all_ok else 1)


if __name__ == '__main__':
    main()
